import { Injectable } from '@nestjs/common';
import { ConfigService } from '@nestjs/config';
import { authenticator } from 'otplib';
import { User } from '@live-chat/shared';
import { toDataURL } from 'qrcode';

/**
 * Service responsible for handling two-factor authentication (2FA) logic.
 * This includes generating 2FA secrets, QR codes, and verifying authentication codes.
 */
@Injectable()
export class TwoFactorAuthenticationService {
  constructor(private readonly configService: ConfigService) {}

  /**
   * Generates a new 2FA secret and an OTP (One-Time Password) authentication URL for a user.
   * The secret is not saved at this stage; it's returned for the user to confirm.
   *
   * @param user - The user for whom to generate the 2FA secret.
   * @returns A promise that resolves to an object containing the generated secret and the OTP authentication URL.
   */
  public async generateSecret(
    user: User
  ): Promise<{ secret: string; otpAuthUrl: string }> {
    const secret = authenticator.generateSecret();
    const appName = this.configService.get<string>(
      'TWO_FACTOR_APP_NAME',
      'LiveChat'
    );
    const otpAuthUrl = authenticator.keyuri(user.email, appName, secret);

    // We don't save the secret yet. It will be saved only after user confirms the code.
    return { secret, otpAuthUrl };
  }

  /**
   * Generates a Data URL for a QR code from an OTP authentication URL.
   * This Data URL can be used to display the QR code image directly in a web page.
   *
   * @param otpAuthUrl - The OTP authentication URL generated by `generateSecret`.
   * @returns A promise that resolves to a string containing the Data URL of the QR code.
   */
  public async generateQrCodeDataURL(otpAuthUrl: string): Promise<string> {
    return toDataURL(otpAuthUrl);
  }

  /**
   * Verifies if a provided 2FA code is valid against a given secret.
   *
   * @param code - The 2FA code entered by the user.
   * @param secret - The 2FA secret associated with the user.
   * @returns A boolean indicating whether the code is valid.
   */
  public isCodeValid(code: string, secret: string): boolean {
    return authenticator.verify({
      token: code,
      secret: secret,
    });
  }
}
